[theme]
base                     = "light"
primaryColor             = "#A72A11"
backgroundColor          = "#F7F3ED"
secondaryBackgroundColor = "#F0E7DA"
textColor                = "#1F1B17"
font                     = "sans serif"
